# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

jobs:
  build:

    macos:
      xcode: 11.4.0

    steps:
      - checkout
      - run:
          name: Run tests
          command:  |
            cd ios/PurchasesHybridCommon 
            pod install
            fastlane scan
          environment:
            SCAN_SCHEME: PurchasesHybridCommonTests
      - store_test_results:
          path: test_output
      - store_artifacts:
          path: test_output
          destination: scan-output
